server:
  port: 8080
spring:
  application:
    name: "UserX"
  devtools:
    add-properties: false
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8080"
