server:
  port: 8080
spring:
  application:
    name: "UserX"
  devtools:
    add-properties: false
  profiles:
    include: null
  redis:
    host: "localhost"
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapter:
  rest:
    timeout: 5000
    url: "https://reqres.in/api/users"
  sqs:
    region: ${AWS_REGION}
    queueUrl: ${SQS_QUEUE_URL}
    endpoint: ${AWS_ENDPOINT}
  postgresql:
    host: "localhost"
    port: 5432
    database: ${POSTGRES_DB}
    schema: ${POSTGRES_SCHEMA}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
